"""Stage 4: turn the JSON results into the two artefacts the slides consume.

1. figures/alignment_vs_recall.png
   The headline finding: how well an attribution profile matches domain
   knowledge (E1 lift) tracks how well the detector transfers to the unseen
   attacks of KDDTest+.
2. slides/numbers.tex
   Every number quoted on a slide is defined here, so the deck can never drift
   away from the code output.
"""

from __future__ import annotations

import json
import pathlib

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
FIG, RESULTS, SLIDES = ROOT / "figures", ROOT / "results", ROOT / "slides"


def main() -> None:
    SLIDES.mkdir(exist_ok=True)
    met = json.loads((RESULTS / "metrics.json").read_text())
    xai = json.loads((RESULTS / "xai_eval.json").read_text())
    rf = met["models"]["random_forest"]
    mlp = met["models"]["mlp"]
    e1, e2, e34 = (xai["E1_protocol_consistency"], xai["E2_faithfulness"],
                   xai["E3_E4_stability_cost"])

    fams = ["DoS", "Probe", "R2L", "U2R"]
    lift = [e1[f]["lift"] for f in fams]
    recall = [rf["test_per_class_recall"][f] for f in fams]

    fig, ax = plt.subplots(figsize=(5.6, 3.3))
    x = np.arange(len(fams))
    ax.bar(x - 0.19, lift, 0.38, label="explanation/domain alignment (lift)",
           color="#1b4f72")
    ax.bar(x + 0.19, recall, 0.38, label="recall on unseen KDDTest+",
           color="#b0b8c4")
    ax.axhline(1.0, color="#c0392b", lw=0.9, ls="--")
    ax.text(-0.38, 1.04, "lift = 1 (no alignment)", fontsize=7, color="#c0392b",
            ha="left")
    ax.set_xticks(x, fams)
    ax.set_ylabel("value")
    ax.legend(frameon=False, fontsize=8, loc="upper right")
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    fig.tight_layout()
    fig.savefig(FIG / "alignment_vs_recall.png", dpi=170)
    plt.close(fig)

    rho = float(np.corrcoef(lift, recall)[0, 1])

    def cmd(name: str, value) -> str:
        return f"\\newcommand{{\\{name}}}{{{value}}}"

    lines = [
        "% auto-generated by src/report.py - do not edit",
        cmd("nTrain", f"{met['n_train']:,}".replace(",", "\\,")),
        cmd("nTest", f"{met['n_test_official']:,}".replace(",", "\\,")),
        cmd("nCols", met["n_encoded_columns"]),
        cmd("nFields", met["n_semantic_fields"]),
        cmd("rfVal", f"{rf['val_accuracy'] * 100:.1f}"),
        cmd("rfTest", f"{rf['test_accuracy'] * 100:.1f}"),
        cmd("mlpVal", f"{mlp['val_accuracy'] * 100:.1f}"),
        cmd("mlpTest", f"{mlp['test_accuracy'] * 100:.1f}"),
        cmd("recDoS", f"{rf['test_per_class_recall']['DoS'] * 100:.0f}"),
        cmd("recProbe", f"{rf['test_per_class_recall']['Probe'] * 100:.0f}"),
        cmd("recRTL", f"{rf['test_per_class_recall']['R2L'] * 100:.0f}"),
        cmd("recUTR", f"{rf['test_per_class_recall']['U2R'] * 100:.0f}"),
        cmd("nExplained", json.loads(
            (RESULTS / "shap_global.json").read_text())["n_explained"]),
        cmd("aopcShap", f"{e2['aopc']['shap']:.2f}"),
        cmd("aopcLime", f"{e2['aopc']['lime']:.2f}"),
        cmd("aopcRand", f"{e2['aopc']['random']:.2f}"),
        cmd("dropTopThree", f"{e2['curves']['shap'][3]:.2f}"),
        cmd("nFaith", e2["n_flows"]),
        cmd("stabLime", f"{e34['stability_top5_jaccard']['lime']:.2f}"),
        cmd("stabShap", f"{e34['stability_top5_jaccard']['treeshap']:.2f}"),
        cmd("msTree", f"{e34['cost_ms_per_flow']['treeshap_rf']:.0f}"),
        cmd("msLime", f"{e34['cost_ms_per_flow']['lime_rf_1000_samples']:.0f}"),
        cmd("msKernel",
            f"{e34['cost_ms_per_flow']['kernelshap_mlp_256_samples']:.0f}"),
        cmd("jacSL", f"{e34['shap_vs_lime']['top5_jaccard']:.2f}"),
        cmd("rhoSL", f"{e34['shap_vs_lime']['spearman_rho']:+.2f}"),
        cmd("corrAlign", f"{rho:.2f}"),
    ]
    # LaTeX macro names may not contain digits, so R2L/U2R get alpha aliases.
    alias = {"DoS": "DoS", "Probe": "Probe", "R2L": "RTL", "U2R": "UTR"}
    for f in fams:
        lines += [cmd(f"lift{alias[f]}", f"{e1[f]['lift']:.2f}"),
                  cmd(f"share{alias[f]}",
                      f"{e1[f]['attributed_share_in_expected'] * 100:.0f}"),
                  cmd(f"base{alias[f]}",
                      f"{e1[f]['random_baseline_share'] * 100:.0f}")]

    (SLIDES / "numbers.tex").write_text("\n".join(lines) + "\n")
    print(f"wrote {SLIDES / 'numbers.tex'} ({len(lines)} macros)")
    print(f"corr(lift, recall) over 4 families = {rho:.2f}")


if __name__ == "__main__":
    main()
